//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDynamicDLL
{
    using System;
    
    
    public class TestClass1
    {
        
        public System.Nullable<int> TestFieldInt;
    }
    
    public class TestClass2
    {
        
        public string TestFieldString;
        
        public float TestFieldFloat;
        
        public double TestFieldDouble;
    }
    
    public class TestClass3
    {
        
        public System.Collections.Generic.List<string> TestFieldList;
        
        public TestClass2 TestFieldTestClass2;
    }
}
