//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDynamicDLL
{
    using System;
    
    
    public class Rocket
    {
        
        public int range;
        
        public string name;
        
        public string message;
        
        public string fuel;
        
        public string speed;
        
        public System.Collections.Generic.List<string> payload;
    }
}
